# Generated by Django 2.0.6 on 2020-05-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20200526_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('desk_id', models.IntegerField(db_column='desk', primary_key=True, serialize=False)),
                ('floor', models.IntegerField(db_column='floor')),
                ('plug_state', models.IntegerField(choices=[(0, '有插座'), (1, '无插座')], db_column='plug')),
                ('rent_state', models.IntegerField(choices=[(0, '未被占用'), (1, '被占用')], db_column='status')),
            ],
            options={
                'verbose_name_plural': '座位',
                'db_table': 'desk',
            },
        ),
        migrations.CreateModel(
            name='FloorBuilding',
            fields=[
                ('floor', models.IntegerField(primary_key=True, serialize=False)),
                ('number_max', models.IntegerField(db_column='max')),
                ('number_now', models.IntegerField(db_column='now')),
            ],
            options={
                'verbose_name_plural': '楼层',
                'db_table': 'floor',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.IntegerField(choices=[(8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00')], db_column='start_time')),
                ('end_time', models.IntegerField(choices=[(8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00')], db_column='end_time')),
                ('operate_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, '尚未使用'), (1, '正被使用'), (2, '使用结束'), (3, '已取消')], db_column='status')),
                ('desk_number_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seat.Desk')),
                ('user_number_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'verbose_name_plural': '预约座位信息',
                'db_table': 'rent',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rent',
            unique_together={('user_number_id', 'desk_number_id', 'date', 'start_time', 'end_time')},
        ),
    ]
