# Generated by Django 2.0.6 on 2020-05-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='desk_number',
            new_name='desk_number_id',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='user_number',
            new_name='user_number_id',
        ),
        migrations.AlterField(
            model_name='rent',
            name='end_time',
            field=models.IntegerField(choices=[(8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00')], db_column='end_time'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_time',
            field=models.IntegerField(choices=[(8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00')], db_column='start_time'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.IntegerField(choices=[(0, '尚未使用'), (1, '正被使用'), (2, '使用结束'), (3, '已取消')], db_column='status'),
        ),
        migrations.AlterUniqueTogether(
            name='rent',
            unique_together={('user_number_id', 'desk_number_id', 'date', 'start_time', 'end_time')},
        ),
    ]
